<?php
return array(
    0 =>
        array(
            'inspect_grade' => 'A',
            'spot_grade' => 'S-1',
            'apply_no' => '201910311018',
            'po' => '20191015',
            'sku' => '1010190001911',
            'inspect_type' => '客诉',
            'dev_imgs' => 'http://192.168.71.146:5000/file/file/download/image?filePath=group1/M01/00/74/wKhHklyy2yKACRYIAABmhW955IY712.jpg',
            'inspect_detail_address' => '龙岗区五和大道8888号',
            'title_cn' => '飞机大炮EF',
            'devp_type' => '',
            'supplier_name' => '深圳市鸟怒拉斯公司',
            'real_purchase_num' => '12',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '3',
            'is_abnormal' => '正常',
            'inspector' => '杨钦-13715',
            'product_inspect_time' => '2020-03-06',
            'applicant' => '王威-12561',
            'purchase_apply_time' => '0000-00-00 00:00:00',
            'unqualify_type' => '配件不良',
            'unqualify_reason' => '不良99',
            'improve_measure' => '加强产品质量把关',
            'inspect_remark' => '供应商态度良好',
            'duty_dept' => '开发部,品控部',
            'duty_user' => '开发部,品控部',
            'is_lead_inspect' => '是',
            'inspect_result' => '不合格',
        ),
    1 =>
        array(
            'inspect_grade' => 'A',
            'spot_grade' => 'S-1',
            'apply_no' => '201910301019',
            'po' => '20191030',
            'sku' => '1010190016211',
            'inspect_type' => '客诉',
            'dev_imgs' => 'http://192.168.71.104:5000/file/file/download/image?filePath=group1/M01/00/99/wKhHkl0cU6qAYYSOAASIWdmmCjk301.jpg',
            'inspect_detail_address' => '龙岗区五和大道8888号',
            'title_cn' => 'test商品品控-0703-yqa1',
            'devp_type' => '常规',
            'supplier_name' => '深圳市鸟怒拉斯公司',
            'real_purchase_num' => '43',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '2',
            'is_abnormal' => '正常',
            'inspector' => '-',
            'product_inspect_time' => '0000-00-00',
            'applicant' => '王威-12561',
            'purchase_apply_time' => '0000-00-00 00:00:00',
            'unqualify_type' => '',
            'unqualify_reason' => '',
            'improve_measure' => '',
            'inspect_remark' => '',
            'duty_dept' => '',
            'duty_user' => '',
            'is_lead_inspect' => '否',
            'inspect_result' => '待排期',
        ),
    2 =>
        array(
            'inspect_grade' => 'A',
            'spot_grade' => 'S-1',
            'apply_no' => '201910301019',
            'po' => '20191030',
            'sku' => '1010190016212',
            'inspect_type' => '客诉',
            'dev_imgs' => 'http://192.168.71.104:5000/file/file/download/image?filePath=group1/M01/00/99/wKhHkl0cU6qAYYSOAASIWdmmCjk301.jpg',
            'inspect_detail_address' => '龙岗区五和大道8888号',
            'title_cn' => 'test商品品控-0703-yqb1',
            'devp_type' => '常规',
            'supplier_name' => '深圳市鸟怒拉斯公司',
            'real_purchase_num' => '11',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '3',
            'is_abnormal' => '正常',
            'inspector' => '-',
            'product_inspect_time' => '0000-00-00',
            'applicant' => '王威-12561',
            'purchase_apply_time' => '0000-00-00 00:00:00',
            'unqualify_type' => '',
            'unqualify_reason' => '',
            'improve_measure' => '',
            'inspect_remark' => '',
            'duty_dept' => '',
            'duty_user' => '',
            'is_lead_inspect' => '否',
            'inspect_result' => '待排期',
        ),
    3 =>
        array(
            'inspect_grade' => 'S',
            'spot_grade' => 'S-1',
            'apply_no' => '201910311020',
            'po' => '20191038',
            'sku' => '1011190004611',
            'inspect_type' => '客诉',
            'dev_imgs' => 'end/upload/image/productImages/8a8e83cd1619af937b19f91c0a9dde08.jpg',
            'inspect_detail_address' => '龙岗区五和大道8888号',
            'title_cn' => '2019秋款童装打底衫纯棉 儿童长袖男童T恤中小宝宝体恤孩子的衣服3109-花灰/蓝色90cm',
            'devp_type' => '常规',
            'supplier_name' => '深圳市鸟怒拉斯公司',
            'real_purchase_num' => '12',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '3',
            'is_abnormal' => '正常',
            'inspector' => '陈磊-14485',
            'product_inspect_time' => '2020-03-06',
            'applicant' => '王威-12561',
            'purchase_apply_time' => '0000-00-00 00:00:00',
            'unqualify_type' => '配件不良',
            'unqualify_reason' => '不良99',
            'improve_measure' => '加强产品质量把关',
            'inspect_remark' => '',
            'duty_dept' => '开发部,品控部',
            'duty_user' => '开发部,品控部',
            'is_lead_inspect' => '是',
            'inspect_result' => '申请转合格通过',
        ),
    4 =>
        array(
            'inspect_grade' => 'A',
            'spot_grade' => 'Ⅱ',
            'apply_no' => 'YH-2020031900006',
            'po' => 'PO8601876',
            'sku' => 'JY15488',
            'inspect_type' => '首单',
            'dev_imgs' => '',
            'inspect_detail_address' => '上剑山村杨梅大道800号中国邮政二楼xxx',
            'title_cn' => NULL,
            'devp_type' => '',
            'supplier_name' => '福安市时上元素工艺品有限公司',
            'real_purchase_num' => '0',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '0',
            'is_abnormal' => '异常',
            'inspector' => '陈磊-14485',
            'product_inspect_time' => '0000-00-00',
            'applicant' => '彭光基13066-13066',
            'purchase_apply_time' => '2020-03-19 17:17:21',
            'unqualify_type' => '',
            'unqualify_reason' => '',
            'improve_measure' => '',
            'inspect_remark' => '',
            'duty_dept' => '',
            'duty_user' => '',
            'is_lead_inspect' => '是',
            'inspect_result' => '不合格',
        ),
    5 =>
        array(
            'inspect_grade' => 'A',
            'spot_grade' => 'Ⅱ',
            'apply_no' => 'YH-2020031900006',
            'po' => 'PO8601876',
            'sku' => 'JY15491',
            'inspect_type' => '首单',
            'dev_imgs' => '',
            'inspect_detail_address' => '上剑山村杨梅大道800号中国邮政二楼xxx',
            'title_cn' => NULL,
            'devp_type' => '',
            'supplier_name' => '福安市时上元素工艺品有限公司',
            'real_purchase_num' => '0',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '0',
            'is_abnormal' => '异常',
            'inspector' => '陈磊-14485',
            'product_inspect_time' => '0000-00-00',
            'applicant' => '彭光基13066-13066',
            'purchase_apply_time' => '2020-03-19 17:17:21',
            'unqualify_type' => '',
            'unqualify_reason' => '',
            'improve_measure' => '',
            'inspect_remark' => '',
            'duty_dept' => '',
            'duty_user' => '',
            'is_lead_inspect' => '是',
            'inspect_result' => '不合格',
        ),
    6 =>
        array(
            'inspect_grade' => 'S',
            'spot_grade' => 'Ⅱ',
            'apply_no' => 'YH-2020032400007',
            'po' => 'PO100757979',
            'sku' => '101019HS43011',
            'inspect_type' => '首单',
            'dev_imgs' => 'end/upload/image/productImages/57643eeb5b694f524c8758783644eccb.jpg',
            'inspect_detail_address' => '上剑山村杨梅大道800号中国邮政二楼xxx',
            'title_cn' => 'test111s1111111111111',
            'devp_type' => '常规',
            'supplier_name' => '宁波市海曙定及金属制品有限公司',
            'real_purchase_num' => '20',
            'real_collect_num' => '0',
            'unqualify_num' => '0',
            'short_supply_num' => '8',
            'is_abnormal' => '正常',
            'inspector' => '付荣-13718',
            'product_inspect_time' => '2020-03-31',
            'applicant' => '彭光基13066-13066',
            'purchase_apply_time' => '2020-03-24 11:37:01',
            'unqualify_type' => '',
            'unqualify_reason' => '',
            'improve_measure' => '',
            'inspect_remark' => '',
            'duty_dept' => '',
            'duty_user' => '',
            'is_lead_inspect' => '否',
            'inspect_result' => '待验货',
        ),
);

?>